"""add deleted_at column to card

Revision ID: 127bf8e74ba0
Revises: db2df56e7717
Create Date: 2022-01-03 15:52:16.218112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '127bf8e74ba0'
down_revision = 'db2df56e7717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'deleted_at')
    # ### end Alembic commands ###
