"""establishs relationship

Revision ID: 14e335ad0c13
Revises: 555e439a9fe9
Create Date: 2021-12-23 11:09:56.754163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14e335ad0c13'
down_revision = '555e439a9fe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('board_id')
    )
    op.create_table('card',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['board.board_id'], ),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.drop_table('Board')
    op.drop_table('Card')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Card',
    sa.Column('card_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Card_card_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('likes_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('card_id', name='Card_pkey')
    )
    op.create_table('Board',
    sa.Column('board_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Board_board_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('board_id', name='Board_pkey')
    )
    op.drop_table('card')
    op.drop_table('board')
    # ### end Alembic commands ###
