"""empty message

Revision ID: 57425b50f67f
Revises: 07e5fd387ad5
Create Date: 2021-12-23 10:13:13.176429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57425b50f67f'
down_revision = '07e5fd387ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('board_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'card', 'board', ['board_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'board_id')
    # ### end Alembic commands ###
