"""established relationship between models

Revision ID: 62acf6a2cf53
Revises: a833794fc822
Create Date: 2021-12-20 17:49:36.921018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62acf6a2cf53'
down_revision = 'a833794fc822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('board_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'card', 'board', ['board_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'board_id')
    # ### end Alembic commands ###
