"""empty message

Revision ID: 65afbc450453
Revises: e2de60647ba4
Create Date: 2022-01-04 08:50:59.093476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65afbc450453'
down_revision = 'e2de60647ba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('board',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.String(length=250), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('card',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('board_id', sa.Integer(), nullable=False),
    # sa.Column('value', sa.String(), nullable=False),
    # sa.Column('num_likes', sa.Integer(), nullable=True),
    # sa.Column('date', sa.Date(), nullable=True),
    # sa.ForeignKeyConstraint(['board_id'], ['board.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('card')
    # op.drop_table('board')
    # ### end Alembic commands ###
    pass
