"""empty message

Revision ID: 7b35b8502702
Revises: 57425b50f67f
Create Date: 2021-12-29 17:15:00.172039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b35b8502702'
down_revision = '57425b50f67f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('likes', sa.Integer(), nullable=True))
    op.drop_column('card', 'increase_likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('increase_likes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('card', 'likes')
    # ### end Alembic commands ###
