"""adds Board and Card models

Revision ID: a46bbe059e03
Revises: 
Create Date: 2021-12-19 17:15:23.778005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a46bbe059e03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('board', 'board_id')
    op.add_column('card', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('card', 'card_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('card_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('card', 'id')
    op.add_column('board', sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('board', 'id')
    # ### end Alembic commands ###
