"""empty message

Revision ID: b12561208bfa
Revises: 8d4feb05599e
Create Date: 2022-01-03 15:29:09.053888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b12561208bfa'
down_revision = '8d4feb05599e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('timestamp', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'timestamp')
    # ### end Alembic commands ###
