"""add deleted column to card

Revision ID: db2df56e7717
Revises: 9272aae2e4c8
Create Date: 2022-01-03 15:19:05.967007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db2df56e7717'
down_revision = '9272aae2e4c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'deleted')
    # ### end Alembic commands ###
