"""empty message

Revision ID: e8f9819d7932
Revises: b12561208bfa
Create Date: 2022-01-03 15:34:54.146002

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e8f9819d7932'
down_revision = 'b12561208bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('date', sa.Date(), nullable=True))
    op.drop_column('card', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('card', 'date')
    # ### end Alembic commands ###
