"""registered board and card blueprints and updated their models with one to many relationship


Revision ID: fcd438f14673
Revises: 65caa7923d5a
Create Date: 2021-12-21 20:27:32.574925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd438f14673'
down_revision = '65caa7923d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('owner', sa.String(), nullable=True))
    op.add_column('board', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('board', 'message')
    op.drop_column('board', 'likes_count')
    op.add_column('card', sa.Column('board_id', sa.Integer(), nullable=True))
    op.add_column('card', sa.Column('likes_count', sa.Integer(), nullable=True))
    op.add_column('card', sa.Column('message', sa.String(), nullable=True))
    op.create_foreign_key(None, 'card', 'board', ['board_id'], ['board_id'])
    op.drop_column('card', 'title')
    op.drop_column('card', 'owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('owner', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('card', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'message')
    op.drop_column('card', 'likes_count')
    op.drop_column('card', 'board_id')
    op.add_column('board', sa.Column('likes_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('board', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('board', 'title')
    op.drop_column('board', 'owner')
    # ### end Alembic commands ###
